services:
  - type: web
    name: seat-reservation-service
    env: docker
    plan: free
    region: oregon
    branch: master
    healthCheckPath: /health/ready
    envVars:
      - key: PORT
        value: 8080
      - key: DB_URL
        fromDatabase:
          name: seat-reservation-db
          property: connectionString
      - key: DB_USERNAME
        fromDatabase:
          name: seat-reservation-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: seat-reservation-db
          property: password

databases:
  - name: seat-reservation-db
    databaseName: seat_reservation
    user: seat_reservation_user
    plan: free
    region: oregon
